# create Dockerfile to build image of Node js alpine
FROM node:16-alpine
# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application to the container
COPY . .
ENV PATH /app/node_modules/.bin:$PATH
# Expose port 3000
EXPOSE 3000

# Start the application
CMD [ "npm", "run", "dev" ]